<?xml version="1.0" encoding="utf-8"?><Database Name="GymGame_db" Class="GymGameModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\GymGame_db.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GymGame_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Answers" Member="Answers">
    <Type Name="Answer">
      <Column Name="Answer_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Answer_Text" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FK_Question" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Answer_value" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Answer_Result" Member="Results" ThisKey="Answer_Id" OtherKey="FK_Answer" Type="Result" />
      <Association Name="Question_Answer" Member="Question" ThisKey="FK_Question" OtherKey="Question_Id" Type="Question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Questions" Member="Questions">
    <Type Name="Question">
      <Column Name="Question_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Question_Text" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FK_Round" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Question_Answer" Member="Answers" ThisKey="Question_Id" OtherKey="FK_Question" Type="Answer" />
      <Association Name="Question_Result" Member="Results" ThisKey="Question_Id" OtherKey="FK_Question" Type="Result" />
      <Association Name="Round_Question" Member="Round" ThisKey="FK_Round" OtherKey="Round_Id" Type="Round" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Quizzes" Member="Quizs">
    <Type Name="Quiz">
      <Column Name="Quiz_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_Users" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Quiz_Result" Member="Results" ThisKey="Quiz_Id" OtherKey="FK_Quiz" Type="Result" />
      <Association Name="Quiz_Round" Member="Rounds" ThisKey="Quiz_Id" OtherKey="FK_Quiz" Type="Round" />
      <Association Name="User1_Quiz" Member="User" ThisKey="FK_Users" OtherKey="User_Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Results" Member="Results">
    <Type Name="Result">
      <Column Name="Result_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_User" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_Question" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_Answer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_Quiz" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Answer_Result" Member="Answer" ThisKey="FK_Answer" OtherKey="Answer_Id" Type="Answer" IsForeignKey="true" />
      <Association Name="Question_Result" Member="Question" ThisKey="FK_Question" OtherKey="Question_Id" Type="Question" IsForeignKey="true" />
      <Association Name="Quiz_Result" Member="Quiz" ThisKey="FK_Quiz" OtherKey="Quiz_Id" Type="Quiz" IsForeignKey="true" />
      <Association Name="User1_Result" Member="User" ThisKey="FK_User" OtherKey="User_Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="Role_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="RoleCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Role_User1" Member="Users" ThisKey="Role_Id" OtherKey="FK_Role" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Rounds" Member="Rounds">
    <Type Name="Round">
      <Column Name="Round_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_Quiz" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Max_Time" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Round_name" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Association Name="Round_Question" Member="Questions" ThisKey="Round_Id" OtherKey="FK_Round" Type="Question" />
      <Association Name="Quiz_Round" Member="Quiz" ThisKey="FK_Quiz" OtherKey="Quiz_Id" Type="Quiz" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="User_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FK_Role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FB_UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User1_Quiz" Member="Quizs" ThisKey="User_Id" OtherKey="FK_Users" Type="Quiz" />
      <Association Name="User1_Result" Member="Results" ThisKey="User_Id" OtherKey="FK_User" Type="Result" />
      <Association Name="Role_User1" Member="Role" ThisKey="FK_Role" OtherKey="Role_Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
</Database>